name: Render.com release

on:
    push:
        branches: ['main']

jobs:
    release:
        runs-on: ubuntu-latest

        needs: test

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Deploy
              # Only run this step if the branch is main
              if: github.ref == 'refs/heads/main'
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: curl "$deploy_url"
