name: Integration Tests

on:
    push:
        branches:
            - '*'

    pull_request:
        branches: ['main']

jobs:
    release:
        runs-on: ubuntu-latest

        # strategy:
        #     matrix:
        #         node-version: [20.x, 22.x]
        #         mongodb-version: ['6.0', '7.0', '8.0']

        strategy:
            matrix:
                node-version: [20.x]
                mongodb-version: [6.x]

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.12.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Install dependencies
              run: yarn install --production=false

            - name: Generate build
              run: yarn build

            # - name: Remove node_modules
            #   run: rm -rf node_modules

            - name: Run jest tests
              run: yarn test

            - name: Install production dependencies
              run: yarn install --production --frozen-lockfile
